import React                 from "react";
import { ServerStyleSheets } from "@material-ui/core/styles";
import reactRevealconfig     from "react-reveal/globals";
import Document, {
	Html,
	Head,
	Main,
	NextScript,
} from "next/document";

// Import Own Components
import theme from "~/Util/theme";

// To prevent flickering with React Reveal library
reactRevealconfig({
	ssrFadeout : true,
});

class CustomDocument extends Document {
	render() {
		return (
			<Html>
				<Head>
					{ /* App primary color */ }
					<meta name="theme-color" content={theme.palette.primary.main} />

					<link href="https://fonts.googleapis.com/css2?family=Sora:wght@600&display=swap" rel="stylesheet" />
				</Head>

				<body>
					<Main />
					<NextScript />
				</body>
			</Html>
		);
	}
}

// This webapp, has SSR, the following code handles ssr logic
// to handle css styles generated by material ui
CustomDocument.getInitialProps = async (ctx) => {
	const sheets             = new ServerStyleSheets();
	const originalRenderPage = ctx.renderPage;

	ctx.renderPage = () => originalRenderPage({
		enhanceApp : App => props => sheets.collect(<App {...props} />),
	});

	const initialProps = await Document.getInitialProps(ctx);

	return {
		...initialProps,
		// Styles fragment is rendered after the app and page rendering finish.
		styles : [...React.Children.toArray(initialProps.styles), sheets.getStyleElement()],
	};
};

export default CustomDocument;
